### ISSUE TITLE
Unity project is missing all the .meta files.

### ISSUE THREAD

**Issue by srcnalt** [SCRN-VRC/3D-Face-Landmark-in-UnityCG-HLSL#1]
Hi,

I wanted to give this project a try in Unity however there is no .meta file in the Unity project included in the repo, which are crucial for loading. All the materials and prefabs lost their connections to their targets due to this.

**Comment by SCRN-VRC** [comment]
Sorry I just added them back in. If you have any more problems you can try the unity package in release.

**Comment by srcnalt** [comment]
Ah thank you so much, didn't notice the release! I was trying to boot it up from the _FaceLandmarkDetection_ folder.
